/** AUTO-GENERATED by fixture:build from the production fixture owner. */
import type * as Domain from "@nof1-causal-lab/api-types";
declare const value: readonly Domain.SimulationReport[];
export default value;
