/** AUTO-GENERATED by fixture:build from the production fixture owner. */
import type * as Domain from "@nof1-causal-lab/api-types";
import type { BinaryFixture } from "@/components/__fixtures__/fixture-value";
declare const value: BinaryFixture<readonly Domain.SimulationReport[]>;
export default value;
