/** AUTO-GENERATED by fixture:build from the production fixture owner. */
import type * as Domain from "@nof1-causal-lab/api-types";
import type { BinaryFixture } from "@/components/__fixtures__/fixture-value";
declare const value: BinaryFixture<Readonly<Partial<Record<number, Domain.ModelSnapshot>>>>;
export default value;
